export const CONNECTED = "CONNECTED";
export const DISCONNECTED = "DISCONNECTED";
export const CONNECTING = "CONNECTING";
export const CONNECTION_FAILED = "CONNECTION_FAILED";

export const USER_CREATION_REQUESTED = "USER_CREATION_REQUESTED";
export const USER_CREATION_COMPLETED = "USER_CREATION_COMPLETED";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";

export const CHARACTER_FETCH_REQUESTED = "CHARACTER_FETCH_REQUESTED";
export const CHARACTER_FETCH_COMPLETED = "CHARACTER_FETCH_COMPLETED";
export const CHARACTER_FETCH_FAILED = "CHARACTER_FETCH_FAILED";
export const CHARACTER_DELETE_REQUESTED = "CHARACTER_DELETE_REQUESTED";
export const CHARACTER_DELETE_COMPLETED = "CHARACTER_DELETE_COMPLETED";