export const CONNECTED = "CONNECTED";
export const DISCONNECTED = "DISCONNECTED";
export const CONNECTING = "CONNECTING";
export const CONNECTION_FAILED = "CONNECTION_FAILED";

export const USER_CREATION_REQUESTED = "USER_CREATION_REQUESTED";
export const USER_CREATION_COMPLETED = "USER_CREATION_COMPLETED";
export const USER_CREATION_FAILED = "USER_CREATION_FAILED";