name: Open Rpg
on: [push, pull_request]
jobs:
  build:
    name: Open Rpg CI Build
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        node_version: [12.16.1]
        mongodb_version: [4.2]
        os: [ubuntu-latest]
    steps:
      #----------------------------------------------------------------------
      # Install all tools and check configuration
      #----------------------------------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: superchargejs/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb_version }}
      #----------------------------------------------------------------------
      # Back
      #----------------------------------------------------------------------
      - name: 'BACK: Installing project'
        run: mvn -B package --file pom.xml -ntp
      - name: 'BACK: Running tests'
        run: mvn test
      #----------------------------------------------------------------------
      # Front
      #----------------------------------------------------------------------
      - name: 'FRONT: Installing project'
        run: npm install
      - name: 'FRONT Running tests'
        run: npm run test -- --watchAll=false --passWithNoTests
